on: [push]
name: Test
jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download
        run: go mod download
      - name: Vet
        run: go vet github.com/vron/v2d/...
      - name: Test
        run: go test github.com/vron/v2d/...
      - name: Test race
        run: go test -race github.com/vron/v2d/...

  fmt:
    name: Code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fmt
        run: test -z $(go fmt github.com/vron/v2d/...)
